################################################################################
# 02_modeling.R
#
# Simplified Bayesian modeling workflow for PCR and DePCR
#
# Main steps:
#   1. Prepare PCR and DePCR datasets
#   2. Define reference levels
#   3. Fit final distributional negative binomial models
#   4. Fit constant-shape negative binomial models
#   5. Compare models with PSIS-LOO
#   6. Extract posterior summaries
#   7. Generate posterior expected values for exploratory transfer
################################################################################

################################################################################
# 0. PACKAGES
################################################################################

library(brms)
library(rstan)
library(loo)
library(posterior)
library(dplyr)
library(tidyr)
library(ggplot2)

set.seed(10231991)

options(mc.cores = parallel::detectCores())

################################################################################
# 1. INPUT DATA
################################################################################

# The object `data` should contain the processed primer-template count table.
#
# Required variables include:
#
# Counts
# Exp
# Temp
# Protocol
# group
# p3_status
# mid_status
# p5_status
# log_total_counted
#
# The exact data import step depends on the output generated by the
# preprocessing workflow.

################################################################################
# 2. PRIMARY MODELING DATA
################################################################################

# Primary model development uses experiments A10 and A64.

data_model <- data %>%
  filter(
    Exp %in% c("A10", "A64"),
    total_counted > 13000
  )

# PCR and DePCR are modeled separately.

data_PCR <- data_model %>%
  filter(Protocol == "PCR")

data_DePCR <- data_model %>%
  filter(Protocol == "DePCR")

################################################################################
# 3. DEFINE REFERENCE LEVELS
################################################################################

prepare_factors <- function(df) {

  df %>%
    mutate(
      Exp = relevel(factor(Exp), ref = "A10"),
      Temp = relevel(factor(Temp), ref = "45C"),
      group = relevel(factor(group), ref = "A_T_C"),
      p3_status = relevel(factor(p3_status), ref = "Match"),
      mid_status = relevel(factor(mid_status), ref = "Match"),
      p5_status = relevel(factor(p5_status), ref = "Match")
    )
}

data_PCR   <- prepare_factors(data_PCR)
data_DePCR <- prepare_factors(data_DePCR)

################################################################################
# 4. MODEL SETTINGS
################################################################################

control_settings <- list(
  adapt_delta = 0.99,
  max_treedepth = 15
)

################################################################################
# 5. FINAL DISTRIBUTIONAL NEGATIVE BINOMIAL MODEL
################################################################################

# Mean:
# Counts ~ sequencing-depth offset + experiment + temperature +
#          complete three-position primer configuration
#
# Shape:
# shape ~ experiment + temperature +
#         mismatch status at the three evaluated positions

final_formula <- bf(
  Counts ~ offset(log_total_counted) + Exp + Temp + group,
  shape ~ Exp + Temp + p3_status + mid_status + p5_status
)

################################################################################
# 6. FIT FINAL PCR MODEL
################################################################################

fit_PCR <- brm(
  formula = final_formula,
  data = data_PCR,
  family = negbinomial(link = "log"),
  chains = 4,
  iter = 4000,
  warmup = 1000,
  seed = 10231991,
  backend = "rstan",
  control = control_settings,
  save_pars = save_pars(all = TRUE)
)

################################################################################
# 7. FIT FINAL DePCR MODEL
################################################################################

fit_DePCR <- brm(
  formula = final_formula,
  data = data_DePCR,
  family = negbinomial(link = "log"),
  chains = 4,
  iter = 4000,
  warmup = 1000,
  seed = 10231991,
  backend = "rstan",
  control = control_settings,
  save_pars = save_pars(all = TRUE)
)

################################################################################
# 8. MODEL SUMMARIES
################################################################################

summary(fit_PCR)
summary(fit_DePCR)

################################################################################
# 9. CONSTANT-SHAPE NEGATIVE BINOMIAL MODELS
################################################################################

# These models use the same mean structure as the final models but assume
# a single negative binomial shape parameter for all observations.

constant_shape_formula <- bf(
  Counts ~ offset(log_total_counted) + Exp + Temp + group,
  shape ~ 1
)

fit_PCR_NB <- brm(
  formula = constant_shape_formula,
  data = data_PCR,
  family = negbinomial(link = "log"),
  chains = 4,
  iter = 4000,
  warmup = 1000,
  seed = 10231991,
  backend = "rstan",
  control = control_settings,
  save_pars = save_pars(all = TRUE)
)

fit_DePCR_NB <- brm(
  formula = constant_shape_formula,
  data = data_DePCR,
  family = negbinomial(link = "log"),
  chains = 4,
  iter = 4000,
  warmup = 1000,
  seed = 10231991,
  backend = "rstan",
  control = control_settings,
  save_pars = save_pars(all = TRUE)
)

################################################################################
# 10. PSIS-LOO
################################################################################

loo_PCR_distNB <- loo(fit_PCR)
loo_PCR_NB     <- loo(fit_PCR_NB)

loo_DePCR_distNB <- loo(fit_DePCR)
loo_DePCR_NB     <- loo(fit_DePCR_NB)

################################################################################
# 11. DISTRIBUTIONAL VS CONSTANT-SHAPE MODEL
################################################################################

comp_PCR <- loo_compare(
  list(
    NB_distributional = loo_PCR_distNB,
    NB = loo_PCR_NB
  )
)

comp_DePCR <- loo_compare(
  list(
    NB_distributional = loo_DePCR_distNB,
    NB = loo_DePCR_NB
  )
)

print(comp_PCR)
print(comp_DePCR)

################################################################################
# 12. OPTIONAL: SAVE FINAL MODELS
################################################################################

dir.create(
  "results/model_fits",
  recursive = TRUE,
  showWarnings = FALSE
)

saveRDS(
  fit_PCR,
  "results/model_fits/final_model_PCR.rds"
)

saveRDS(
  fit_DePCR,
  "results/model_fits/final_model_DePCR.rds"
)

saveRDS(
  fit_PCR_NB,
  "results/model_fits/constant_shape_NB_PCR.rds"
)

saveRDS(
  fit_DePCR_NB,
  "results/model_fits/constant_shape_NB_DePCR.rds"
)

################################################################################
# 13. SAVE LOO COMPARISONS
################################################################################

dir.create(
  "results/model_comparison",
  recursive = TRUE,
  showWarnings = FALSE
)

write.table(
  as.data.frame(comp_PCR),
  "results/model_comparison/distributional_vs_NB_PCR.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = TRUE
)

write.table(
  as.data.frame(comp_DePCR),
  "results/model_comparison/distributional_vs_NB_DePCR.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = TRUE
)

################################################################################
# 14. POSTERIOR COEFFICIENT TABLES
################################################################################

PCR_parameters <- as.data.frame(
  posterior_summary(
    fit_PCR,
    probs = c(0.025, 0.975)
  )
)

DePCR_parameters <- as.data.frame(
  posterior_summary(
    fit_DePCR,
    probs = c(0.025, 0.975)
  )
)

PCR_parameters$parameter <- rownames(PCR_parameters)
DePCR_parameters$parameter <- rownames(DePCR_parameters)

rownames(PCR_parameters) <- NULL
rownames(DePCR_parameters) <- NULL

write.table(
  PCR_parameters,
  "results/model_comparison/final_PCR_parameters.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  DePCR_parameters,
  "results/model_comparison/final_DePCR_parameters.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

################################################################################
# 15. EXPLORATORY TRANSFER DATA
################################################################################

# A27 retains the ST0 template but uses a different primer pool.
# B10 and B27 contain multiple templates.

transfer_data <- data %>%
  filter(
    Exp %in% c("A27", "B10", "B27")
  )

transfer_data <- prepare_factors(transfer_data)

################################################################################
# 16. POSTERIOR EXPECTED VALUES
################################################################################

# posterior_epred() returns the expected value of the response for each
# posterior draw and observation.
#
# allow_new_levels = TRUE can be required when applying the model to data
# containing factor levels not present during model development.

PCR_transfer <- transfer_data %>%
  filter(Protocol == "PCR")

DePCR_transfer <- transfer_data %>%
  filter(Protocol == "DePCR")

epred_PCR <- posterior_epred(
  fit_PCR,
  newdata = PCR_transfer,
  allow_new_levels = TRUE
)

epred_DePCR <- posterior_epred(
  fit_DePCR,
  newdata = DePCR_transfer,
  allow_new_levels = TRUE
)

################################################################################
# 17. POSTERIOR EXPECTED COUNT
################################################################################

PCR_transfer$predicted <- colMeans(epred_PCR)
DePCR_transfer$predicted <- colMeans(epred_DePCR)

################################################################################
# 18. EXTRACT TEMPLATE ID
################################################################################

# Example feature:
#
# B10_ST00V00
#
# Template identifier:
#
# B10_ST00

PCR_transfer <- PCR_transfer %>%
  mutate(
    template = sub("V[0-9]+.*$", "", id_feature)
  )

DePCR_transfer <- DePCR_transfer %>%
  mutate(
    template = sub("V[0-9]+.*$", "", id_feature)
  )

################################################################################
# 19. CONVERT COUNTS TO WITHIN-TEMPLATE PROPORTIONS
################################################################################

PCR_transfer <- PCR_transfer %>%
  group_by(Exp, Temp, template) %>%
  mutate(
    raw_counts_percent =
      100 * Counts / sum(Counts),

    pred_counts_percent =
      100 * predicted / sum(predicted)
  ) %>%
  ungroup()

DePCR_transfer <- DePCR_transfer %>%
  group_by(Exp, Temp, template) %>%
  mutate(
    raw_counts_percent =
      100 * Counts / sum(Counts),

    pred_counts_percent =
      100 * predicted / sum(predicted)
  ) %>%
  ungroup()

################################################################################
# 20. SAVE TRANSFER PREDICTIONS
################################################################################

dir.create(
  "results/predictions",
  recursive = TRUE,
  showWarnings = FALSE
)

write.table(
  PCR_transfer,
  "results/predictions/PCR_transfer_predictions.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  DePCR_transfer,
  "results/predictions/DePCR_transfer_predictions.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

################################################################################
# 21. BASIC OBSERVED VS PREDICTED PLOT
################################################################################

ggplot(
  PCR_transfer,
  aes(
    x = raw_counts_percent,
    y = pred_counts_percent
  )
) +
  geom_abline(
    intercept = 0,
    slope = 1,
    linetype = "dashed"
  ) +
  geom_point(
    aes(
      shape = p3_status
    ),
    alpha = 0.7
  ) +
  facet_grid(
    template ~ Exp + Temp,
    scales = "free"
  ) +
  labs(
    x = "Observed proportion (%)",
    y = "Predicted proportion (%)",
    title = "PCR exploratory transfer"
  ) +
  theme_bw()

ggplot(
  DePCR_transfer,
  aes(
    x = raw_counts_percent,
    y = pred_counts_percent
  )
) +
  geom_abline(
    intercept = 0,
    slope = 1,
    linetype = "dashed"
  ) +
  geom_point(
    aes(
      shape = p3_status
    ),
    alpha = 0.7
  ) +
  facet_grid(
    template ~ Exp + Temp,
    scales = "free"
  ) +
  labs(
    x = "Observed proportion (%)",
    y = "Predicted proportion (%)",
    title = "DePCR exploratory transfer"
  ) +
  theme_bw()

################################################################################
# END
################################################################################
